### PR TITLE
Fix strong mode errors.

### PR DESCRIPTION
**Pull request by a-siva**

### CODE REVIEW

**Comment by keertip** [comment]
@renggli , this fix uses the cast method, which was introduced in 2.0.0-dev.23.0. To apply this fix, the lower constraints for the sdk would have to be changed to 2.0.0-dev.23. Would that be ok?

**Comment by renggli** [comment]
If we change the SDK constraints, does that mean that users of Dart 1.x that depend on this package will get the old version?

**Comment by kevmoo** [comment]
> If we change the SDK constraints, does that mean that users of Dart 1.x that depend on this package will get the old version?

They won't get this release – and future releases, true.

**Comment by renggli** [comment]
SGTM regarding the SDK constraints, but now the problem is that Travis fails. Would it be possible to use `each[0] as List<TNode>` instead of `each[0].cast<TNode>()`?

**Comment by vsmenon** [comment]
An `as` would fail at runtime (`each[0]` is not a `List<TNode>` per Dart 2).

Something like:
```
new List<TNode>.from(each[0])
```

should work on both though.

**Comment by aam** [comment]
Do you want to graduate it from `-alpha` too? Once this lands, this will be used in `flutter`.

**Comment by renggli** [comment]
Yes, I will do that :-)

**Comment by a-siva** [comment]
Any updates on landing the fix for this?

**Comment by a-siva** [comment]
Addressed code review comments, PTAL.

**Comment by renggli** [comment]
I've committed the changes proposed in this pull request and modified them slightly to make the code backward compatible in 66d41af4a97b1747b90ae340cf8f50478ba0a955.

However, running the XML tests themselves still yields a lot of failing tests, which seems mostly related to the visitors used for copying and normalizing the XML tree: 

```
$ dart --preview-dart-2 test/all_tests.dart
...
00:01 +64 -164: XML examples shiporder [E]
  type 'XmlTransformer' is not a subtype of type 'XmlVisitor<XmlNode>' where
    XmlTransformer is from package:xml/xml/visitors/transformer.dart
    XmlVisitable is from package:xml/xml/visitors/visitable.dart
    XmlVisitor is from package:xml/xml/visitors/visitor.dart
    XmlNode is from package:xml/xml/nodes/node.dart
  
  package:xml/xml/visitors/visitor.dart                         XmlVisitor.visit
  package:xml/xml/nodes/node.dart 88:44                         XmlNode.copy
  test/xml_test.dart 212:18                                     assertCopyInvariants
  test/xml_test.dart 50:3                                       assertTreeInvariants
  test/xml_test.dart 27:3                                       assetParseInvariants
  test/xml_test.dart 2214:7                                     main.<fn>.<fn>
  package:test/src/backend/declarer.dart 161:27                 Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  ...
```

**Comment by renggli** [comment]
Not sure how to fix those visitors? There seems to be something really messed up with how they are currently typed.

**Comment by renggli** [comment]
The only solution I found so far is declaring all return types in the visitors as dynamic. b57543698dc3585155a5960618550c05065a0d4c passes all tests.

**Comment by renggli** [comment]
Ok, I've merged all proposed changes, fixed all tests and published 3.0.0 that works with old Dart, Dart 2.0 and `--preview-dart-2`.

**Comment by keertip** [comment]
Thank you @renggli

**Pull request closed without merging**
