### PR TITLE
Allow update after reading XML file

### PR DESCRIPTION
**Pull request by sestegra**
After reading XML file, it's not possible to update it.
See code below.

```
node.children.insert(insert, newNode);
Unsupported operation: Cannot add from a fixed-length list
#0      ListBase&&FixedLengthListMixin.removeAt (dart:_internal/list.dart:61)
```

### CODE REVIEW

**Comment by sestegra** [comment]
I need this feature to implement small updates for ODS & XLSX files.
Impacted project is [spreadsheet_decoder](https://github.com/sestegra/spreadsheet_decoder)

**Comment by renggli** [comment]
`XmlNode`s are designed as immutable entities and trying to modify them breaks all kind of assumptions throughout the code. Normally `XmlTransformer` subclasses are used to transform node trees.

**Comment by sestegra** [comment]
My case is following:
- read global XML file
- add attributes and children to few nodes of global XML file
- write back the updated file

I don't get how to do this without reading whole XML file at step 2.

**Comment by sestegra** [comment]
I'm working to create ```MutableXmlDocument``` and  ```MutableXmlParent``` to support my case.

**Comment by renggli** [comment]
I am guess you can hack the library easily to make it mutable, however to get it working properly you will need to rewrite most of it and test all kind of edge cases (moving nodes, updating parents, dealing with validation, ...).

The following example shows how to do a transformation with the existing code. It first parses `books.xml`. Then it adds an attribute and removes an element from each book, before writing it out again. If you want to build more complicated sub-trees the XmlBuilder can also be helpful.

```dart
import 'package:xml/xml.dart';
import 'xml_examples.dart';

class UpdateBooks extends XmlTransformer {
  @override
  XmlElement visitElement(XmlElement node) {
    if (node.name.qualified == 'book') {
      return new XmlElement(
          visit(node.name),
          // Add a new attribute.
          visitAll(new List.from(node.attributes)
              ..add(new XmlAttribute(new XmlName('lang'), 'en'))),
          // Remove elements meeting a particular condition.
          visitAll(node.children
              .where((node) => !(node is XmlElement && node.name.qualified == 'description'))));
    }
    return super.visitElement(node);
  }
}

void main() {
  var original = parse(booksXml);
  var transformed = new UpdateBooks().visit(original);
  print(transformed);
}

```

**Comment by sestegra** [comment]
See #29 for my update.

My case is most complex, I have to update Excel or OpenOffice document. I can't rebuild all document each time I need to update a cell.

For more information, you can have a look of my current working branch on spreadsheet_decoder.
https://github.com/sestegra/spreadsheet_decoder/tree/update

**Comment by renggli** [comment]
Just my thought, but I think you miss some abstraction over XML. Did you consider creating a proper mutable object model with `Speadsheet`, `Column`, `Row`, `Cell`, ... classes that hold the respective pointers into the XML document. You then mutate this model, and at the end you recursively traverse it with a XmlBuilder and recreate the appropriate XML document.

**Comment by sestegra** [comment]
Thank you for your feedback, I will try on that way.

**Comment by sestegra** [comment]
I'm using mutable-dom branch now.
Thank you for your support.

**Pull request closed without merging**
