### PR TITLE
Fix entites escape

### PR DESCRIPTION
**Pull request by pinnisi**
Original code only encodes < and &, others were missing

### CODE REVIEW

**Comment by renggli** [comment]
Thank you for your pull request, but as far as I understand in text only "<" and "&" need to be escaped, see here: https://www.w3.org/TR/xml11/#syntax.

**Comment by pinnisi** [comment]
I have to send an xml (with his own CDATA) encoded in a text value of another xml, If I not escape ">" I get an invalid xml.

"The right angle bracket (>) may be represented using the string "&gt;", and must, for compatibility, be escaped using either "&gt;" or a character reference when it appears in the string "]]>" in content, when that string is not marking the end of a CDATA section."

**Comment by renggli** [comment]
Good point, but you change does way more than that and breaks some tests.

**Comment by pinnisi** [comment]
If it's ok I'll rewrite my changes to be less "aggressive" and not breaking
tests

Il 27 lug 2017 10:31 PM, "Lukas Renggli" <notifications@github.com> ha
scritto:

**Pull request closed without merging**
